### ISSUE TITLE
Is sbt-rjs dead?

### ISSUE THREAD

**Issue by codeape** [sbt/sbt-rjs#76]
Clearly a lot of people use sbt-rjs but why is it not maintained. The build is broken when looking at Travis. Why are not the pull request even looked at? 4 months and no new release on this?

In this post you want people to to try sbt-rjs with sbt 1.4 https://github.com/sbt/sbt-web/issues/118. Sbt-web 1.4.0 and sbt-rjs 1.0.8 does not work together.

Is this project dead?
Do you need help?
#66 #68 #69 #71 #75

@huntc @jroper

**Comment by ndimas** [comment]
+1

**Comment by hiepnsx** [comment]
+1

**Comment by lglossman-ring** [comment]
+1

**Comment by lglossman** [comment]
+1

**Comment by Mule52** [comment]
+1

**Comment by adrianhurt** [comment]
+10

**Comment by benblack86** [comment]
+1

**Comment by driverpt** [comment]
+1

**Comment by adrianhurt** [comment]
I think we have to assume it is

**Comment by danielnixon** [comment]
I get the impression the whole sbt-web ecosystem is dead. See also [sbt-uglify](https://github.com/sbt/sbt-uglify) or [sbt-less](https://github.com/sbt/sbt-less), for example.

**Comment by huntc** [comment]
It really isn't. Please accept my apologies for the lack of response. We've just not had the time to give this the attention that it needs.

**Comment by LeonhardtDavid** [comment]
@huntc can we help with something? The plugins are very useful, but they are mostly outdated. It's a shame if no one can manage them.

**Comment by alaz** [comment]
Frankly, I have a similar impression about Play Framework as well -
* [500 error not worth fixing](https://github.com/playframework/playframework/issues/4878)
* [conditional requests not needed](https://github.com/playframework/playframework/issues/6296) (Rails [has it](http://guides.rubyonrails.org/caching_with_rails.html#conditional-get-support) since version 2.3 or maybe even earlier; that's 2008-2009)

Play and sbt-web quickly become a technical debt.

**Comment by benmccann** [comment]
The build is passing again now. Thanks @danielnixon and @bjoernhaeuser for the tips on that

**Comment by benmccann** [comment]
I've upgraded to sbt-web 1.4.0 and sbt-js-engine 1.2.0. I'm doing this across all the sbt-web plugins. I hope this addresses the majority of the issues
